# Generated by Django 6.0.5 on 2026-06-29 04:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='TraceEvent',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('event_type', models.CharField(choices=[('planting', '种植'), ('fertilizing', '施肥'), ('pesticide', '农药'), ('harvest', '采收'), ('qc', '质检'), ('storage', '入库'), ('shipping', '发货'), ('other', '其他')], default='other', max_length=30)),
                        ('title', models.CharField(max_length=120)),
                        ('description', models.TextField(blank=True)),
                        ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                        ('location', models.CharField(blank=True, max_length=200)),
                        ('previous_hash', models.CharField(blank=True, max_length=64)),
                        ('data_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='products.productbatch')),
                        ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'db_table': 'core_traceevent',
                        'ordering': ['occurred_at', 'created_at'],
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
