# Generated by Django 6.0.5 on 2026-06-29 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='FarmingGuide',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('title', models.CharField(max_length=200, verbose_name='标题')),
                        ('category', models.CharField(choices=[('planting', '种植技术'), ('pest', '病虫害防治'), ('fertilizer', '施肥管理'), ('harvest', '采收储存'), ('storage', '保鲜运输'), ('other', '其他')], default='other', max_length=20, verbose_name='分类')),
                        ('crop_type', models.CharField(choices=[('rice', '水稻'), ('wheat', '小麦'), ('corn', '玉米'), ('fruit', '水果'), ('vegetable', '蔬菜'), ('tea', '茶叶'), ('herb', '中药材'), ('livestock', '畜禽'), ('aquatic', '水产'), ('general', '通用')], default='general', max_length=20, verbose_name='适用作物')),
                        ('content', models.TextField(verbose_name='内容')),
                        ('cover_image', models.CharField(blank=True, max_length=500, verbose_name='封面图片URL')),
                        ('is_published', models.BooleanField(default=True, verbose_name='是否发布')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                    ],
                    options={
                        'verbose_name': '农业技术指南',
                        'verbose_name_plural': '农业技术指南',
                        'db_table': 'core_farmingguide',
                        'ordering': ['-created_at'],
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
