# Generated by Django 6.0.5 on 2026-05-28 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='review_note',
            field=models.TextField(blank=True, help_text='审核意见'),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('pending', '待审核'), ('approved', '已上架'), ('rejected', '未通过')], default='draft', max_length=20),
        ),
    ]
