# Generated by Django 6.0.5 on 2026-05-28 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product_review_note_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='产品图片', null=True, upload_to='products/'),
        ),
    ]
