# Generated by Django 6.0.5 on 2026-05-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbatch',
            name='qr_code',
            field=models.ImageField(blank=True, help_text='溯源二维码', null=True, upload_to='qrcodes/'),
        ),
    ]
