# Generated by Django 6.0.5 on 2026-05-29 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_productbatch_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbatch',
            name='qr_code',
        ),
    ]
