# Generated by Django 6.0.5 on 2026-05-29 08:52

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_productbatch_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbatch',
            name='batch_code',
            field=models.CharField(default=core.models.generate_batch_code, max_length=100, unique=True),
        ),
    ]
