# Generated by Django 6.0.5 on 2026-06-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_traceevent_qr_review_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否显示')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='快递单号'),
        ),
        migrations.AddField(
            model_name='productbatch',
            name='qc_images',
            field=models.JSONField(blank=True, default=list, verbose_name='质检图片'),
        ),
        migrations.AddField(
            model_name='productbatch',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('pending', '待质检'), ('approved', '已通过'), ('rejected', '未通过')], default='draft', max_length=20, verbose_name='批次状态'),
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='qc_report',
            field=models.CharField(blank=True, max_length=500, verbose_name='质检报告'),
        ),
    ]
