# Generated by Django 6.0.5 on 2026-06-25 03:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='farm_photos',
            field=models.JSONField(blank=True, default=list, help_text='农场照片URL列表', verbose_name='农场照片'),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='farm_story',
            field=models.TextField(blank=True, help_text='介绍你的农场历史、种植理念等', verbose_name='农场故事'),
        ),
        migrations.CreateModel(
            name='FarmingGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('category', models.CharField(choices=[('planting', '种植技术'), ('pest', '病虫害防治'), ('fertilizer', '施肥管理'), ('harvest', '采收储存'), ('storage', '保鲜运输'), ('other', '其他')], default='other', max_length=20, verbose_name='分类')),
                ('crop_type', models.CharField(choices=[('rice', '水稻'), ('wheat', '小麦'), ('corn', '玉米'), ('fruit', '水果'), ('vegetable', '蔬菜'), ('tea', '茶叶'), ('herb', '中药材'), ('livestock', '畜禽'), ('aquatic', '水产'), ('general', '通用')], default='general', max_length=20, verbose_name='适用作物')),
                ('content', models.TextField(verbose_name='内容')),
                ('cover_image', models.CharField(blank=True, max_length=500, verbose_name='封面图片URL')),
                ('is_published', models.BooleanField(default=True, verbose_name='是否发布')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '农业技术指南',
                'verbose_name_plural': '农业技术指南',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PreOrderCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='产品名称')),
                ('description', models.TextField(verbose_name='活动描述')),
                ('cover_image', models.CharField(blank=True, max_length=500, verbose_name='封面图片URL')),
                ('target_quantity', models.PositiveIntegerField(verbose_name='目标数量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='原价')),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='预售价')),
                ('unit', models.CharField(default='kg', max_length=50, verbose_name='单位')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间')),
                ('end_date', models.DateTimeField(verbose_name='结束时间')),
                ('harvest_date', models.DateField(blank=True, null=True, verbose_name='预计采收日期')),
                ('current_quantity', models.PositiveIntegerField(default=0, verbose_name='已预订数量')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '进行中'), ('ended', '已结束'), ('cancelled', '已取消')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preorder_campaigns', to='core.farmerprofile')),
            ],
            options={
                'verbose_name': '预售活动',
                'verbose_name_plural': '预售活动',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplyDemandPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('supply', '供应'), ('demand', '需求')], max_length=20, verbose_name='帖子类型')),
                ('product_name', models.CharField(max_length=200, verbose_name='产品名称')),
                ('category', models.CharField(help_text='例如：水果、蔬菜、粮油、茶叶等', max_length=100, verbose_name='产品分类')),
                ('quantity', models.PositiveIntegerField(verbose_name='数量')),
                ('unit', models.CharField(default='kg', max_length=50, verbose_name='单位')),
                ('price_range', models.CharField(blank=True, help_text='例如：10-15元/kg', max_length=100, verbose_name='价格区间')),
                ('region', models.CharField(max_length=200, verbose_name='所在地区')),
                ('description', models.TextField(verbose_name='详细描述')),
                ('status', models.CharField(choices=[('active', '进行中'), ('closed', '已关闭')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_demand_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '供需对接帖子',
                'verbose_name_plural': '供需对接帖子',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PreOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='预订数量')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总金额')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('address', models.CharField(max_length=300, verbose_name='收货地址')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preorders', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preorders', to='core.preordercampaign')),
            ],
            options={
                'verbose_name': '预售订单',
                'verbose_name_plural': '预售订单',
                'ordering': ['-created_at'],
                'unique_together': {('campaign', 'buyer')},
            },
        ),
    ]
