# Generated by Django 6.0.5 on 2026-06-26 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_supply_demand_guide_preorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbatch',
            name='batch_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='批次编码'),
        ),
    ]
