# Generated by Django 6.0.5 on 2026-06-29 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_update_content_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_type', models.CharField(choices=[('farmer', '农户入驻'), ('cooperative', '合作社入驻')], max_length=20, verbose_name='申请类型')),
                ('name', models.CharField(max_length=200, verbose_name='姓名/合作社名称')),
                ('phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('region', models.CharField(max_length=200, verbose_name='所在地区')),
                ('description', models.TextField(blank=True, verbose_name='简介（产品/规模/特色）')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='审核状态')),
                ('reviewer_note', models.TextField(blank=True, verbose_name='审核备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_joinapplication',
                'ordering': ['-created_at'],
            },
        ),
    ]
