# Generated by Django 6.0.5 on 2026-06-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_join_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinapplication',
            name='apply_type',
            field=models.CharField(choices=[('farmer', '农户入驻')], max_length=20, verbose_name='申请类型'),
        ),
    ]
