# Generated by Django 6.0.5 on 2026-06-30 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_cooperative'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='joinapplication',
            name='farm_photos',
            field=models.JSONField(blank=True, default=list, verbose_name='农场/产品照片'),
        ),
        migrations.AddField(
            model_name='joinapplication',
            name='id_document',
            field=models.ImageField(blank=True, null=True, upload_to='applications/id_docs/', verbose_name='身份证/户口本'),
        ),
        migrations.AddField(
            model_name='joinapplication',
            name='license_document',
            field=models.ImageField(blank=True, null=True, upload_to='applications/licenses/', verbose_name='营业执照/资质证明'),
        ),
        migrations.AddField(
            model_name='joinapplication',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='join_applications', to=settings.AUTH_USER_MODEL, verbose_name='申请人'),
        ),
    ]
