# Generated by Django 6.0.5 on 2026-06-29 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Cart',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'db_table': 'core_cart',
                    },
                ),
                migrations.CreateModel(
                    name='CartItem',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('quantity', models.PositiveIntegerField(default=1)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='trade.cart')),
                        ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                    ],
                    options={
                        'db_table': 'core_cartitem',
                    },
                ),
                migrations.CreateModel(
                    name='Order',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                        ('status', models.CharField(choices=[('pending', 'pending'), ('paid_offline', 'paid_offline'), ('confirmed', 'confirmed'), ('shipped', 'shipped'), ('delivered', 'delivered'), ('cancelled', 'cancelled')], default='pending', max_length=20)),
                        ('address', models.CharField(max_length=300)),
                        ('payment_proof', models.CharField(blank=True, max_length=500)),
                        ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='快递单号')),
                        ('shipped_at', models.DateTimeField(blank=True, null=True)),
                        ('delivered_at', models.DateTimeField(blank=True, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'db_table': 'core_order',
                    },
                ),
                migrations.CreateModel(
                    name='LogisticsEvent',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('status', models.CharField(max_length=100)),
                        ('timestamp', models.DateTimeField(auto_now_add=True)),
                        ('location', models.CharField(blank=True, max_length=200)),
                        ('note', models.TextField(blank=True)),
                        ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='trade.order')),
                    ],
                    options={
                        'db_table': 'core_logisticsevent',
                    },
                ),
                migrations.CreateModel(
                    name='OrderItem',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('quantity', models.PositiveIntegerField(default=1)),
                        ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                        ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='trade.order')),
                        ('product_batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productbatch')),
                    ],
                    options={
                        'db_table': 'core_orderitem',
                    },
                ),
                migrations.CreateModel(
                    name='Favorite',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'db_table': 'core_favorite',
                        'unique_together': {('user', 'product')},
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
