# Generated by Django 6.0.5 on 2026-06-29 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='SupplyDemandPost',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('post_type', models.CharField(choices=[('supply', '供应'), ('demand', '需求')], max_length=20, verbose_name='帖子类型')),
                        ('product_name', models.CharField(max_length=200, verbose_name='产品名称')),
                        ('category', models.CharField(help_text='例如：水果、蔬菜、粮油、茶叶等', max_length=100, verbose_name='产品分类')),
                        ('quantity', models.PositiveIntegerField(verbose_name='数量')),
                        ('unit', models.CharField(default='kg', max_length=50, verbose_name='单位')),
                        ('price_range', models.CharField(blank=True, help_text='例如：10-15元/kg', max_length=100, verbose_name='价格区间')),
                        ('region', models.CharField(max_length=200, verbose_name='所在地区')),
                        ('description', models.TextField(verbose_name='详细描述')),
                        ('status', models.CharField(choices=[('active', '进行中'), ('closed', '已关闭')], default='active', max_length=20, verbose_name='状态')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_demand_posts', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'verbose_name': '供需对接帖子',
                        'verbose_name_plural': '供需对接帖子',
                        'db_table': 'core_supplydemandpost',
                        'ordering': ['-created_at'],
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
