# Generated by Django 6.0.5 on 2026-06-30 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_farmerpaymentmethod'),
        ('marketplace', '0001_initial'),
        ('products', '0004_add_wholesale_pricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, help_text='向买家介绍你的产品优势', verbose_name='留言')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('demand_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='marketplace.supplydemandpost')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_responses', to='accounts.farmerprofile')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_responses', to='products.product')),
            ],
            options={
                'verbose_name': '需求响应',
                'verbose_name_plural': '需求响应',
                'db_table': 'core_demandresponse',
                'ordering': ['-created_at'],
            },
        ),
    ]
