# Generated by Django 6.0.5 on 2026-06-29 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='FarmerProfile',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('phone', models.CharField(blank=True, max_length=32)),
                        ('address', models.CharField(blank=True, max_length=300)),
                        ('location_lat', models.FloatField(blank=True, null=True)),
                        ('location_lng', models.FloatField(blank=True, null=True)),
                        ('verified', models.BooleanField(default=False)),
                        ('shop_description', models.TextField(blank=True, verbose_name='店铺简介')),
                        ('shop_avatar', models.ImageField(blank=True, null=True, upload_to='shop_avatars/')),
                        ('farm_story', models.TextField(blank=True, help_text='介绍你的农场历史、种植理念等', verbose_name='农场故事')),
                        ('farm_photos', models.JSONField(blank=True, default=list, help_text='农场照片URL列表', verbose_name='农场照片')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                    ],
                    options={
                        'db_table': 'core_farmerprofile',
                    },
                ),
                migrations.CreateModel(
                    name='SubsidyApplication',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('type', models.CharField(max_length=100)),
                        ('amount_requested', models.DecimalField(decimal_places=2, max_digits=12)),
                        ('documents', models.JSONField(blank=True, default=list)),
                        ('status', models.CharField(choices=[('submitted', 'submitted'), ('approved', 'approved'), ('rejected', 'rejected')], default='submitted', max_length=20)),
                        ('admin_notes', models.TextField(blank=True)),
                        ('submitted_at', models.DateTimeField(auto_now_add=True)),
                        ('decided_at', models.DateTimeField(blank=True, null=True)),
                    ],
                    options={
                        'db_table': 'core_subsidyapplication',
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
