# Generated by Django 6.0.5 on 2026-06-29 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='farmerprofile',
                    name='cooperative',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.cooperative'),
                ),
                migrations.AddField(
                    model_name='farmerprofile',
                    name='user',
                    field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
                migrations.AddField(
                    model_name='subsidyapplication',
                    name='farmer',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsidies', to='accounts.farmerprofile'),
                ),
            ],
            database_operations=[],
        ),
    ]
