# Generated by Django 6.0.5 on 2026-06-29 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='farmerprofile',
                    name='cooperative',
                ),
            ],
            database_operations=[],
        ),
    ]
