# Generated by Django 6.0.5 on 2026-06-30 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_cooperative'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_type', models.CharField(choices=[('wechat', '微信支付'), ('alipay', '支付宝'), ('bank', '银行卡转账')], max_length=20, verbose_name='收款方式')),
                ('account_name', models.CharField(max_length=100, verbose_name='收款人/户名')),
                ('account_number', models.CharField(max_length=100, verbose_name='账号')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='payment_qr/', verbose_name='收款码图片')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='accounts.farmerprofile')),
            ],
            options={
                'db_table': 'core_farmerpaymentmethod',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
    ]
