# Generated by Django 6.0.5 on 2026-06-29 04:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='PreOrderCampaign',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('product_name', models.CharField(max_length=200, verbose_name='产品名称')),
                        ('description', models.TextField(verbose_name='活动描述')),
                        ('cover_image', models.CharField(blank=True, max_length=500, verbose_name='封面图片URL')),
                        ('target_quantity', models.PositiveIntegerField(verbose_name='目标数量')),
                        ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='原价')),
                        ('discount_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='预售价')),
                        ('unit', models.CharField(default='kg', max_length=50, verbose_name='单位')),
                        ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间')),
                        ('end_date', models.DateTimeField(verbose_name='结束时间')),
                        ('harvest_date', models.DateField(blank=True, null=True, verbose_name='预计采收日期')),
                        ('current_quantity', models.PositiveIntegerField(default=0, verbose_name='已预订数量')),
                        ('status', models.CharField(choices=[('draft', '草稿'), ('active', '进行中'), ('ended', '已结束'), ('cancelled', '已取消')], default='active', max_length=20, verbose_name='状态')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preorder_campaigns', to='accounts.farmerprofile')),
                    ],
                    options={
                        'verbose_name': '预售活动',
                        'verbose_name_plural': '预售活动',
                        'db_table': 'core_preordercampaign',
                        'ordering': ['-created_at'],
                    },
                ),
                migrations.CreateModel(
                    name='PreOrder',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('quantity', models.PositiveIntegerField(default=1, verbose_name='预订数量')),
                        ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总金额')),
                        ('status', models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                        ('address', models.CharField(max_length=300, verbose_name='收货地址')),
                        ('note', models.TextField(blank=True, verbose_name='备注')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preorders', to=settings.AUTH_USER_MODEL)),
                        ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preorders', to='preorder.preordercampaign')),
                    ],
                    options={
                        'verbose_name': '预售订单',
                        'verbose_name_plural': '预售订单',
                        'db_table': 'core_preorder',
                        'ordering': ['-created_at'],
                        'unique_together': {('campaign', 'buyer')},
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
