# Generated by Django 6.0.5 on 2026-06-29 04:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Cooperative',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=200)),
                        ('contact', models.CharField(blank=True, max_length=100, null=True)),
                        ('region', models.CharField(blank=True, max_length=200, null=True)),
                        ('verified', models.BooleanField(default=False)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                    ],
                    options={
                        'db_table': 'core_cooperative',
                    },
                ),
                migrations.CreateModel(
                    name='Product',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=200)),
                        ('category', models.CharField(blank=True, max_length=100)),
                        ('variety', models.CharField(blank=True, max_length=100)),
                        ('description', models.TextField(blank=True)),
                        ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                        ('unit', models.CharField(default='kg', max_length=50)),
                        ('image', models.ImageField(blank=True, help_text='产品图片', null=True, upload_to='products/')),
                        ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '待审核'), ('approved', '已上架'), ('rejected', '未通过')], default='draft', max_length=20)),
                        ('review_note', models.TextField(blank=True, help_text='审核意见')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='accounts.farmerprofile')),
                    ],
                    options={
                        'db_table': 'core_product',
                    },
                ),
                migrations.CreateModel(
                    name='ProductBatch',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('batch_code', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='批次编码')),
                        ('harvest_date', models.DateField(blank=True, null=True)),
                        ('quantity', models.PositiveIntegerField(default=0)),
                        ('images', models.JSONField(blank=True, default=list)),
                        ('trace_info', models.JSONField(blank=True, default=dict)),
                        ('qc_report', models.CharField(blank=True, max_length=500, verbose_name='质检报告')),
                        ('qc_images', models.JSONField(blank=True, default=list, verbose_name='质检图片')),
                        ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '待质检'), ('approved', '已通过'), ('rejected', '未通过')], default='draft', max_length=20, verbose_name='批次状态')),
                        ('qr_code', models.ImageField(blank=True, help_text='溯源二维码', null=True, upload_to='qrcodes/')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='products.product')),
                    ],
                    options={
                        'db_table': 'core_productbatch',
                    },
                ),
                migrations.CreateModel(
                    name='Review',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('rating', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                        ('comment', models.TextField(blank=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                        ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.farmerprofile')),
                    ],
                    options={
                        'db_table': 'core_review',
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
