# Generated by Django 6.0.5 on 2026-06-29 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='review',
                    name='order',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.order'),
                ),
                migrations.AddField(
                    model_name='review',
                    name='product',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
                ),
            ],
            database_operations=[],
        ),
    ]
