# Generated by Django 6.0.5 on 2026-06-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_cooperative'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='wholesale_min_quantity',
            field=models.PositiveIntegerField(default=10, verbose_name='批发起订量'),
        ),
        migrations.AddField(
            model_name='product',
            name='wholesale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='批发单价'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='零售单价'),
        ),
    ]
